// GENERATED by 'npm run sim:ratings' — do not edit by hand.
// Bradley–Terry Elo across the rated bot versions, anchored so
// claude-v2 = 0 (the permanent field-floor anchor). Only RELATIVE gaps are
// meaningful; the friendly display offset lives in roles.ts (ratingFor).
// Regenerate whenever a version is added (or to refresh the whole ladder).

export const RATING_ANCHOR = "claude-v2";

export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {
  "claude-v36": 132.6,
  "jane-v2": 126.6,
  "jane-v4": 112.1,
  "jane-v3": 109.5,
  "claude-v21": 89.9,
  "claude-v35": 84.1,
  "claude-v30": 77.9,
  "claude-v18": 76.2,
  "jane-v1": 76.1,
  "claude-v31": 75.5,
  "claude-v32": 75.1,
  "claude-v29": 71.6,
  "claude-v28": 63.3,
  "claude-v24": 63.0,
  "claude-v17": 62.9,
  "claude-v22": 60.7,
  "claude-v11": 59.7,
  "claude-v34": 59.3,
  "claude-v25": 58.4,
  "claude-v6": 58.4,
  "claude-v8": 56.6,
  "claude-v20": 56.3,
  "claude-v10": 56.3,
  "claude-v19": 55.0,
  "claude-v26": 54.2,
  "claude-v33": 53.7,
  "claude-v12": 53.1,
  "claude-v23": 48.8,
  "claude-v5": 45.7,
  "claude-v4": 41.7,
  "claude-v14": 40.9,
  "claude-v27": 39.6,
  "claude-v7": 36.7,
  "claude-v16": 33.3,
  "claude-v9": 23.8,
  "claude-v3": 20.6,
  "claude-v13": 11.7,
  "claude-v15": 0.8,
  "claude-v2": 0.0,
};
