// GENERATED by 'npm run sim:ratings' — do not edit by hand.
// Bradley–Terry Elo across the rated bot versions, anchored so
// claude-v2 = 0 (the permanent field-floor anchor). Only RELATIVE gaps are
// meaningful; the friendly display offset lives in roles.ts (ratingFor).
// Regenerate whenever a version is added (or to refresh the whole ladder).

export const RATING_ANCHOR = "claude-v2";

export const BOT_RATINGS: Readonly<Partial<Record<string, number>>> = {
  "claude-v36": 132.0,
  "jane-v4": 106.7,
  "jane-v2": 94.6,
  "claude-v35": 66.9,
  "jane-v1": 55.1,
  "claude-v2": 0.0,
};
